name: Laravel

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env', '.env');"
    - name: Install Dependencies
      run: composer update || composer install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

  phpUnit-tests:
    name: PHPUnit test
    runs-on: ubuntu-latest

    steps:
    - name: Execute tests units via PHPUnit
<<<<<<< HEAD
=======
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
>>>>>>> be4d1a743692713a7b9441b1116f5c051753996f
      run: php vendor/bin/phpunit tests/Unit

  k6_test:
    name: k6 test run
    runs-on: ubuntu-latest
    container: docker://loadimpact/k6:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Install Docker image
        run: docker pull loadimpact/k6

      - name: K6 Simple test
        run: docker run -i loadimpact/k6 run - < tests/Performance/simple-test.js

      - name: K6 Smoke test
        run: docker run -i loadimpact/k6 run - < tests/Performance/smoke-test.js

      - name: K6 Load test
        run: docker run -i loadimpact/k6 run - < tests/Performance/load-test.js

      - name: K6 Stress test
        run: docker run -i loadimpact/k6 run - < tests/Performance/stress-test.js

      - name: K6 Spike test
        run: docker run -i loadimpact/k6 run - < tests/Performance/spike-test.js

      - name: K6 Soak test
        run: docker run -i loadimpact/k6 run - < tests/Performance/soak-test.js

  pageSpeedInsight_test:
    name: Page Speed Insight test
    runs-on: ubuntu-latest
    steps:
      - name: Running Page Speed Insights
        uses: jakepartusch/psi-action@v1.2
        id: psi
        with:
          url: "http://localhost:8000"
          threshold: 70
          strategy: desktop
          key: no


  blackfire_test:
    name: Blackfire test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Blackfire via setup-php Action
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: blackfire, :xdebug
          # Setup Blackfire Agent and CLI tool, Blackfire Player, and Laravel CLI
          tools: blackfire, blackfire-player, laravel
        env:
          BLACKFIRE_SERVER_ID: ${{ secrets.BLACKFIRE_SERVER_ID }}
          BLACKFIRE_SERVER_TOKEN: ${{ secrets.BLACKFIRE_SERVER_TOKEN }}
          BLACKFIRE_CLIENT_ID: ${{ secrets.BLACKFIRE_CLIENT_ID }}
          BLACKFIRE_CLIENT_TOKEN: ${{ secrets.BLACKFIRE_CLIENT_TOKEN }}

      - name: Laravel local server start
        env:
          APP_ENV: prod
          APP_DEBUG: 0
        run: |
          php artisan serve
          # Run Blackfire Player scenarios from .blackfire.yaml or .bkf files
          blackfire-player run --endpoint=http://localhost:8000 --blackfire-env=<your-blackfire-environment-id> .blackfire.yaml
