name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
    - name: k6 Load Test
      # You may pin to the exact commit or the version.
      # uses: grafana/k6-action@55845c6c2e400af4356c84e5b514aeabb1bfdbd4
      uses: grafana/k6-action@v0.2.0
      with:
      # To run in the k6 cloud, provide your k6 cloud token as a secret to the input `token`.
      # Dont have a k6 account yet? Go to https://k6.io/cloud and activate your free trial.
        cloud: no
        # optional
        # k6 Cloud Token. Only required for using the cloud service.
        token: no
        # optional, default is 
        # Path to the test script to execute, relative to the workspace.
        filename: script.js
        # Additional argument and flags to provide to the k6 CLI. See https://k6.io/docs/using-k6/options for details.
        flags: no
        # optional, default is 
